# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [1]:
import itertools

In [5]:
lst = ['A', 'B', 'C']

list(itertools.combinations(lst, 2))

[('A', 'B'), ('A', 'C'), ('B', 'C')]

**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [6]:
cycle = itertools.cycle(['Python', 'is', 'fun'])

for i in range(10):
    print(next(cycle))

Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [7]:
import glob

python_files = glob.glob('*.py')

print(python_files)

[]


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [9]:
html_doc = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"

from bs4 import BeautifulSoup

soup = BeautifulSoup(html_doc)

soup.find('p').text

'AI is transforming the world'

**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [11]:
import re

def replace_ai_with_artificial_intelligence(text):
    pattern = re.compile(r'\bAI\b')

    replaced_text = re.sub(pattern, 'Artificial Intelligence', text)

    return replaced_text

replace_ai_with_artificial_intelligence("AI is amazing.")

'Artificial Intelligence is amazing.'

**CP6**: Create a numpy array of 10 zeros.

In [15]:
import numpy as np

zeros = np.zeros(10)

print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**CP7** Create a numpy array of the integers from 10 to 49.

In [16]:
rng = np.arange(10, 50)

print(rng)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [19]:
matrix = np.arange(9)
matrix.resize(3, 3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

Machine learning models require large amounts of data to learn complex patterns and generalize well to new, unseen data. A "large" amount of data means having enough examples to effectively learn and generalize the underlying patterns, which varies depending on the problem and model complexity.

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

AI can be used in an adversarial way, such as in adversarial attacks or social engineering. To prevent these attacks, technical measures like developing robust machine learning models, and non-technical measures like educating people and implementing policies can be taken. A comprehensive strategy that considers both technical and non-technical measures is important to prevent adversarial use of AI.